### ISSUE TITLE
Custom buffs icons overlapping with buff texts with new UI/Hud

### ISSUE THREAD

**Issue by Prisma501** [TheWalkingZed/TWZ-Issue-Tracker#1]
CPM's buffs are affected by the new UI/Hud. The buff icon and text overlap. For example "In reset zone".

![image](https://user-images.githubusercontent.com/20812779/151155546-cab62ee2-d27b-4d8d-89e5-24047af88af6.png)

Depending on how text justification is forced on buff labels with the UI, an easy fix could be adding some spaces  in the display value of custom buffs.

`<display_value_key value="[add spaces here] In reset zone"/>`

Location of buffs.xml for CPM -> CPM Mod Folder/Config/buffs.xml

**Comment by PRG-James** [comment]
Holy Smokes, the man himself is in here!!!

**Comment by HiGHeR187** [comment]
Shifted buffs popup window test justification to be right instead of center
