### ISSUE TITLE
Fix - TWZ_Custom_Zombies - Fix

### ISSUE THREAD

**Issue by PRG-James** [TheWalkingZed/TWZ-Issue-Tracker#23]
Remove Configs (with an s) and also README.txt and Mod.xml. Keep Config and keep ModInfo.xml

**Comment by JamesBridgeford** [comment]
@olebem92 Please remove the list of zombies that @HiGHeR187 is going to attach from the spawn lists..

**Comment by HiGHeR187** [comment]
phoenixes are still in some spawn groups, and BM spawns
