### ISSUE TITLE
no allied players able to damage player bases

### ISSUE THREAD

**Issue by Babbs77** [TheWalkingZed/TWZ-Issue-Tracker#35]
However, the explosive damage caused by non allied players was also strangely damaging the blocks, since I didn't see any aoe zombies damaging them.

Babbs ⚔ (7D Officer/Ops) — Today at 12:22 PM
okay so players are able to damage another player base with explosives
[12:22 PM]
That should not be happening (edited)

Can we look into this please - Players should not be able to damage other player bases with a LCB in place

**Comment by olebem92** [comment]
if they are allies then theyll be able to do damage to the base as if it was their own claim. we would have to remove block damage from explosives, which I am totally on board with and could do easily. BUT that removes block damage for all explosives. if not removing it, maybe nerf it?
