### ISSUE TITLE
Zombie Arch0n and Ge1st do not path to player after spawn

### ISSUE THREAD

**Issue by JamesBridgeford** [TheWalkingZed/TWZ-Issue-Tracker#4]
been testing the new zombies on test server. zombie Arch0n and Ge1st both fly in the air. once in the air they dont even acknowledge my location and just fly around

**Comment by HiGHeR187** [comment]
tested to some extent, the problem seems to be that flying zombies are based off the vulture template, and they don't usually attack unless attacked.  playing with it a bit to make them attack
