### ISSUE TITLE
Create Boss Zombies

### ISSUE THREAD

**Issue by JamesBridgeford** [TheWalkingZed/TWZ-Issue-Tracker#44]
Add in the following Boss Zombies

Nuke Boss
Jugernaught
Santa Clause
Frost bite
madusa

Create a boss zombie based on LAB that will be the loot zombie for the Super component

**Comment by HiGHeR187** [comment]
Working, getting bugs out, will post probably tomorrow
@aboan if you can pull listings for things like this, you are really good with decompilier, need the newer updated syntax?
entities/resources/materials/ - capitalization matters
#Other/Items?Misc
entities/furniture/materials/
particleeffects/models/materials
Stuff like that, anything really that you think would make a cool look on bosses
particle effects, models, meshes, etc for: models, entities, materials items
